# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Swift on macos-latest
    # strategy:
    #   matrix:
    #     platform: [macOS, iOS, tvOS, watchOS]
    #     include:
    #       - platform: macOS
    #         destination: 'generic/platform=macOS'
    #         test_cmd: 'swift test'
    #       - platform: iOS
    #         destination: 'platform=iOS Simulator,name=iPhone 14'
    #         test_cmd: 'xcodebuild -scheme DFService test'
    #       - platform: tvOS
    #         destination: 'platform=tvOS Simulator,name=Apple TV 4K'
    #         test_cmd: 'xcodebuild -scheme DFService test'
    #       - platform: watchOS
    #         destination: 'platform=watchOS Simulator,name=Apple Watch Series 7'
    #         test_cmd: 'xcodebuild -scheme DFService test'
    #     os: [macos-12,macos-latest]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v
